on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker
    container:
      image: docker.io/alpine:3.21.2

    steps:
      - uses: actions/checkout@v4
      - name: install needed packages
        run: apk update && apk add --no-cache rsync openssh-client
      - name: install ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_RPIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ vars.SSH_PORT }}" -H "${{ vars.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: test
        run: |
          env
          ls $GITHUB_WORKSPACE

