on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker
    container:
      image: docker.io/alpine:3.21.2

    steps:
      - name: install needed packages
        run: apk update && apk add --no-cache rsync openssh-client nodejs git
      - uses: actions/checkout@v4
      - name: install ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_RPIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ vars.SSH_PORT }}" -H "${{ vars.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: create remote directory
        run: ssh -p "${{ vars.SSH_PORT }}" "${{ vars.SSH_USER }}"@"${{ vars.SSH_HOST }}" 'mkdir -p ${{ vars.SSH_DEPLOY_DIR }}'
      - name: sync .htaccess file
        run: rsync -avzP -e 'ssh -p ${{ vars.SSH_PORT }}' "$GITHUB_WORKSPACE/.htaccess" "${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_DEPLOY_DIR }}/.htaccess"
      - name: sync src folder
        run: rsync -avzP -e 'ssh -p ${{ vars.SSH_PORT }}' "$GITHUB_WORKSPACE/src/" "${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_DEPLOY_DIR }}/src/"
